# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38683c88783d9dd18dc7a8819a5a46042f8a101494cd930d4be0fbc7f45160bacd1b7f38e748f5d1439a49aa06db30df22c8b15dfe6c1a158d25f30beef98faf

test:
  secret_key_base: a03b26b2dc80506283584fa68c8c96e7f1b3002e527a63585d209e568a59e13222080ca5c8d1eded5413c36e6921ce1c1e193dbcc2785e8490edd292dfea4ec7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
